### PR TITLE
Updated aside style and functionality

### PR DESCRIPTION
**Pull request by Lukewh**
## Done

Improved scroll positioning for aside.
Removed style that broke alignment.

## QA

- Modify build-html:11:
`git clone https://github.com/Lukewh/vanilla-framework --branch remove-toc-from-homepage`
- Run `./build-html` followed by `caddy`
- Open http://127.0.0.1:8543/en/patterns/lists
- Ensure the aside still functions.

## Details

Related to: https://github.com/vanilla-framework/vanilla-docs-theme/pull/49
To implement: https://github.com/vanilla-framework/vanilla-docs-theme/issues/1

### CODE REVIEW

**Comment by anthonydillon** [comment]
What about just putting `position: sticky;` on the aside and let older browsers work like normal. Then we would have no javascript.

**Comment by Lukewh** [comment]
@anthonydillon good shout. Done

**Comment by anthonydillon** [comment]
Looks good but I don't see the aside when running with `./build-html`.

**Comment by Lukewh** [comment]
@anthonydillon updated the QA instructions, can you try again when you get a chance? Cheers

**Pull request merged**
