### PR TITLE
Replace old docs.vanillaframework.io method

### PR DESCRIPTION
**Pull request by nottrobin**
Use documentation-builder to build the site, as it will be going forward (even though it won't be done by this repo before too long).

QA
---

Open up `build-html` and edit it so that it says "git clone --branch develop https://github.com/vanilla-framework/vanilla-framework".

Then run the site, following the README. Check it works.

### CODE REVIEW

**Comment by nottrobin** [comment]
[Change docs.vanillaframework.io to building with documentation-builder](https://trello.com/c/9hCRouMm/2533-change-docs-vanillaframework-io-to-building-with-documentation-builder)

**Comment by anthonydillon** [comment]
@barrymcgee would you mind taking a look at this one please.

**Comment by barrymcgee** [comment]
@nottrobin Does your fork still exist? I can't seem to pull it and get a 404 for https://github.com/nottrobin/docs.vanillaframework.io

**Comment by nottrobin** [comment]
@barrymcgee sorry it's there now. It was called "vanillaframework.io" which was the old name for this repo. I've renamed it.

**Comment by barrymcgee** [comment]
@nottrobin I've installed python3 with homebrew but still getting this error:

screen shot 2017-02-20 at 15 45 27

Is there a way (like rvm) to locally switch between python versions?

**Pull request merged**
