### PR TITLE
Improve the table of contents

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Update to the latest docs release v1.6.0. Add the separater class to the Back to top list item. Updated the JS to have the true value so fixed scrolling is smoother.

## QA
- Run `build-html`
- Run `caddy`
- Go to 127.0.0.1:8543/en/base/forms
- Check the table of contents is styled with space
- Scroll down and see that the sticky functionality is smooth

## Details
Fixes https://github.com/vanilla-framework/vanilla-docs-theme/issues/57

### CODE REVIEW

**Comment by yaili** [comment]
@anthonydillon will there be a demo link?

**Comment by anthonydillon** [comment]
This is difficult as it's only works locally. Tomorrow I will spin it up and send you a link.

**Comment by barrymcgee** [comment]
@anthonydillon Examples don't seem to be importing?

screen shot 2017-08-08 at 12 08 24

**Comment by anthonydillon** [comment]
@barrymcgee They are loading ok for me. Could you try again please.

**Comment by anthonydillon** [comment]
Here is a screenshot of the page @yaili 
forms - documentation

**Comment by anthonydillon** [comment]
Showed @yaili and she was happy.

**Comment by anthonydillon** [comment]
After testing it is a local issue on Barrys machine.

**Pull request merged**
