### PR TITLE
Small text changes to index.md

### PR DESCRIPTION
**Pull request by yaili**
Go to index.md and review the copy changes made:

- Consistent reference to "Vanilla Framework"
- Correct capitalisation of GitHub
- Link to Canonical for context
- No full stops in headings

### CODE REVIEW

**Comment by evilnick** [comment]
one small question - do you enforce a word wrap limit on MD format files - it can make the diffs easier to read

**Comment by yaili** [comment]
@evilnick I noticed that different md files seem to have different wrapping. @anthonydillon @barrymcgee ?

**Comment by anthonydillon** [comment]
@yaili yes 80 character line length please.

**Comment by yaili** [comment]
@anthonydillon can that be enforced on github.com UI?

**Comment by barrymcgee** [comment]
@yaili Doesn't it already? https://github.com/blog/1707-soft-wrapping-on-prose-diffs

**Comment by yaili** [comment]
@barrymcgee I think we want hard wrapping. Had a look with Ant, I will try to write in text editor and then paste.

**Comment by evilnick** [comment]
@yaili Yes. Soft wrapping still generates diffs where a single page in a large paragraph highlights the entire paragraph. Most text editors will allow you to set up hard wrapping, or you can just do it manually.

The only thing to watch out for are links - markdown doesn't work so well if you break these over lines!

**Pull request merged**
